### ISSUE TITLE
Mac and Linux distrobutions

### ISSUE THREAD

**Issue by lyricalpaws** [lyricalpaws/Stenoright#1]
Looking for builds of Stenoright for the Mac and Linux, if possible. Submit to `/bin`.

**Comment by HarryET** [comment]
Will try mac now!

**Comment by tullur** [comment]
Hi! I'll work on Linux build

**Comment by lyricalpaws** [comment]
> 
> 
> Hi! I'll work on Linux build

Assigning you now

**Comment by lyricalpaws** [comment]
Once both are added I'll close this issue, thank you both.
If code needs to be changed slgihtly to work for the respective machine, make a subdir in `/bin` and I'll order them.
